### ISSUE TITLE
Updating rows or columns in pie chart leads to wrong visualization

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#96] opened 2019-01-17 08:53 UTC
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
I have a canvas that renders a pie chart with the following config
`
.rows([])
.columns([])
.layers([{
    mark: 'arc',
    encoding: {
       angle: 'count',
     },
  }])
.color('Origin')
`
![image](https://user-images.githubusercontent.com/7683718/51306407-45fffe80-1a63-11e9-9eb5-4c8b0e979ec3.png)

If I update the config to
`
.rows(['Displacement'])
.columns(['origin'])
`

A crosstab of Pie charts is rendered instead of the expectd bar chart.
The layers config (mark as arc) is carried over and there is no way to reset it.
Supplying layers config as `.layers([])` causes an error.

![image](https://user-images.githubusercontent.com/7683718/51306362-2ec11100-1a63-11e9-95a3-fb26e2ee018f.png)

**What is the expected behavior?**
Either the layers config should not carry over or there should be a way to reset it.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by ranajitbanerjee** [comment] 2019-01-22 11:01
@sushrut141  The issue is now fixed. If u call `canvas.layers([])`, then it will reset the layers configuration.

**Closed** 2019-02-01 10:58 UTC
